spec/features/reaccession_via_preassembly_spec.rb
Fixes #13. Added new directory  `dor/staging/integration-tests` with druid vy293gd2473.
n/a
=> Created new druid vy293gd2473 for reaccession/preassembly spec

spec/spec_helper.rb
Default value was 2 seconds which caused things like collection creation to fail occasionally
n/a
=> Increase the time capybara will wait for items before giving up

spec/features/reaccession_via_preassembly_spec.rb
Since media accessioning also goes through preassembly, the files for a given test need to be in a subfolder or everything gets all confused.
and yes, I ran the test locally to ensure it works (and it was broken before since I started adding folders for audio-test and video-test)
na
=> fix reaccession via preassembly spec

README.md, spec/features/create_apo_spec.rb, spec/features/create_collection_spec.rb, spec/features/create_object_no_files_spec.rb, spec/features/sdr_deposit_spec.rb
Whenever possible, our integration tests should 
- create collections from the integration-testing apo
- create objects in the integration-testing collection
This may not be comprehensive, but it's a good start. 
part of #46
na
=> use integration-testing apo and collection objects

.rubocop.yml, .rubocop_todo.yml
So we document our style expectations and don't have exceptions in the rubocop_todo.yml that we don't want to fix.
no.
=> Configure rubocop to allow large rspec blocks

spec/features/create_media_objects_spec.rb
some devs need fully qualified names to get to the correct IP.
na
=> use fully qualified name for preassembly vm in media object test

spec/features/create_apo_spec.rb, spec/features/create_collection_spec.rb, spec/features/create_media_objects_spec.rb, spec/features/create_object_no_files_spec.rb
To speed up tests;  
- no need to wait for registrationWF before using preassembly
- start from the url you really want in Argo
na
=> remove needless waiting and navigation

spec/features/sdr_deposit_spec.rb
Technical metadata is only generated for preserved files now, so in order to make this test pass, we need to mark these files for preservation.
no
=> Set the preservation bit on the deposited files

Gemfile.lock, spec/features/sdr_deposit_spec.rb
The previous invocation is now tripping a validation in dor-services-app that disallows files to be shelved when the access is dark
no
=> Set world access so that shelved files don't conflict with dark

README.md, spec/features/create_etd_spec.rb
Use environment variables to hold credentials.
I have run this spec and can confirm it works.
To restore a useful spec.
Yes
=> Restore ETD spec

.gitignore, Gemfile, Gemfile.lock, README.md, settings.yml, spec/features/create_etd_spec.rb, spec/support/config.rb
Yes, I ran the spec and verified that it works as expected!
This lets us use a single file to store credentials locally so we can set it up once and move on, rather than having to fuss about with environment variables. Thanks to @ndushay for the recommendation!
Yes.
=> Use config files instead of environment variables

.travis.yml, README.md, Rakefile
Default rake task runs the test to match other projects; but travis should still only run rubocop
yes
=> make the default rake task running all the tests with rubocop

.gitignore, Gemfile, Gemfile.lock, README.md, Rakefile, settings.yml, spec/spec_helper.rb
Also:
* Prefer webdrivers gem over manual downloading of drivers
To allow individual developers to exert more control over which browser is used for integration testing. Important especially when a driver (e.g. geckodriver w/ Firefox 76) is misbehaving.
And to remove manual set up steps.
I ran the suite twice, once with each driver. It ran the tests as expected. None of the failures noted were due to changes in this branch, AFAICT.
README.
=> Allow switching between Firefox and Chrome selenium drivers

README.md, settings.yml, spec/features/create_preassembly_image_spec.rb, spec/spec_helper.rb
And fix a pre-assembly spec.
To prevent tests from failing because expected links are collapsed into responsive design elements, and to get the suite passing.
I ran the tests.
README and settings.yml.
=> Set minimum window size for both browsers

.rubocop.yml, spec/features/bulk_update_metadata_spec.rb, spec/features/create_apo_spec.rb, spec/features/create_collection_spec.rb, spec/features/create_object_no_files_spec.rb, spec/features/create_preassembly_image_spec.rb, spec/features/deposit_via_hydrus_spec.rb, spec/features/reaccession_via_preassembly_spec.rb, spec/features/sdr_deposit_spec.rb, spec/spec_helper.rb, spec/support/deposit_helpers.rb, spec/support/page_helpers.rb, spec/support/xlsx_helpers.rb
Connects to #103 
This commit fixes two known bugs:
* Using SdrClient::Deposit.run without handling the background job result ID that is returned. This broke the bulk_update_metadata spec.
* Changing the Argo registration URL (was removed in Argo). This broke two other specs.
As part of this work, pull related code into helpers so it is easier to vary behavior in the future without touching lots of files.
Not necessary.
No.
=> Fix bugs and consolidate code in helpers

settings.yml
All eleven tests pass for me (using ffx driver, not chrome) when I bump these values up in `settings.local.yml`. That suggests to me we ought to consider setting these as the defaults.
No.
No.
=> Bump up timeouts

README.md, spec/spec_helper.rb
Fixes #103
Our tests do not all pass using the Chrome browser. Use Firefox for all tests to reduce variation.
Yes
No
=> Remove support for chrome driver

README.md, spec/spec_helper.rb
Reverts sul-dlss/infrastructure-integration-test#106
It turns out that the ETD app was actually broken, and having Chrome as a driver was very useful. We just didn't know it at the time. @sul-dlss/infrastructure-team
=> Revert "Remove support for chrome driver"

spec/features/create_etd_spec.rb, spec/support/page_helpers.rb
Otherwise it waits for the capybara timeout to expire before looping, causing the whole suite to be very slow
no
no
=> Set a small capybara timeout when inside a refresh loop

spec/support/page_helpers.rb
This mimics the behavior that our end users would experience, and speeds up the test suite.
no
no
=> Use the cache when reloading

spec/features/create_etd_spec.rb
Connects to sul-dlss/hydra_etd#320 (PR is ready for review. Keeping it on hold so it isn't merged until hydra_etd 320 is merged and deployed to stage.)
To test the changes in https://github.com/sul-dlss/hydra_etd/pull/421 
No.
=> Reflect new ETD workflow step

spec/features/create_etd_spec.rb
To test sul-dlss/hydra_etd#386.
No.
No.
=> Update ETD creation spec to account for change made in sul-dlss/hydra_etd#386

.gitignore, README.md, config/settings.yml, config/settings/qa.yml, config/settings/staging.yml, spec/features/bulk_update_metadata_spec.rb, spec/features/create_apo_spec.rb, spec/features/create_collection_spec.rb, spec/features/create_etd_spec.rb, spec/features/create_object_no_files_spec.rb, spec/features/create_preassembly_image_spec.rb, spec/features/deposit_via_hydrus_spec.rb, spec/features/edit_bulk_tags_spec.rb, spec/features/edit_item_tags_spec.rb, spec/features/sdr_deposit_spec.rb, spec/support/authentication_helpers.rb, spec/support/config.rb, spec/support/constants.rb, spec/support/deposit_helpers.rb, spec/support/xlsx_helpers.rb
Connects to #128
I can confirm that all the tests passed for me (after a couple runs, per usual).
To allow running tests in staging and QA per #128.
Yes.
Not shared_configs, no, but local configs have been modified and documented.
=> Allow running tests in both staging and QA environments

spec/features/create_etd_spec.rb
So create_etd test would run cleanly after PR sul-dlss/hydra_etd#666 is deployed to stage
n/a
n/a
=> create_etd: change due to hydra_etd PR 666

spec/features/bulk_update_metadata_spec.rb, spec/features/create_preassembly_image_spec.rb
Includes:
* Squash a bug I introduced due to treating a row of TH elements as a row of TD elements
* Prevent a Selenium stale reference error and allow the bulk update metadata test to pass
* Reload create_preassembly_image page until expected text appears
I can confirm the tests now passes in stage.
No.
No.
=> Find bulk update row without looping

spec/features/create_etd_spec.rb
This allows the test to better simulate the peoplesoft system, when run in different timezones.
n/a
n/a
=> the ETD app always operates in the pacific TZ

spec/features/create_etd_spec.rb
Fixes sul-dlss/hydra_etd#881 (fix the etd integration spec to account for accessibility changes).  Borrowed code from https://github.com/sul-dlss/hydra_etd/blob/master/spec/features/student_submission_spec.rb)
The etd integration spec now passed for me, but would like verification from someone else
No
No
=> fix etd spec to account for accessibility changes

spec/features/sdr_deposit_spec.rb
It was not finding the tech metadata because it was in a collapsed accordion.
=> Expand the techMetadata accordion before looking for entries under it

config/settings.yml
I found I needed this bump to help the QA preassembly test pass.
N/A
no
=> Bump default wf timeout value

spec/features/create_preassembly_image_spec.rb
Fixes #164 (perhaps)
Its possible there is a race condition where we re-accession something in the pre-assembly integration test ... just speculation, though running the test with this fix locally made it work.
No
No
=> Add pause before reaccession

spec/features/create_preassembly_image_spec.rb
The preassembly image spec should be ok with image sizes picked up as a faction of a kb different - change the matcher to use a regex to allow for fractions of a kb difference to still pass.
Noticed this test failing from time to time when the image size in contentMetadata was varying by .1 kb in each direction.  See #162 for a bit more detail.
Fixes #162 
No
No
=> make pre-assembly image spec less brittle

spec/features/create_object_h2_spec.rb
so the test in question can upload a file, otherwise, test errors like:
```
1) Use H2 to create an object is expected to have text "Deposit your content"
Failure/Error:
attach_file('spec/fixtures/sul-logo.png') do
find('div.dropzone').click
end
ArgumentError:
Capybara was unable to determine the file input you're attaching to
```
n/a
n/a
=> H2 spec: click on the 'Choose files' button instead of on the drop zone

README.md
This repo does not use .org.
Yes
No
=> Change CI badge to point at paid Travis service

spec/features/create_etd_spec.rb
This was required to get the ETD spec to pass, though I have also seen it flap in other ways which this PR does not attempt to fix because not always reproducible.
=> Scope modal closing in ETD spec to containing div

Gemfile, Gemfile.lock
`sdr_deposit_spec.rb` was failing because the version of sdr-client in use before this PR had a slight incompatibility with sdr-api after it was upgraded to rails 6.1.
see also https://github.com/sul-dlss/sdr-client/pull/146
n/a
n/a
=> upgrade sdr-client to address compat issue with rails upgraded sdr-api

Gemfile, Gemfile.lock, spec/features/create_object_h2_spec.rb, spec/spec_helper.rb
The previous method found any table with the collection title in it. This was a problem because there are now two tables on the page with that text.  This finds just the table that has the collection name as it's caption.
=> Find the h2 table with the caption

spec/features/create_object_h2_spec.rb
Found that this test currently fails due to not including the required license field on collection and the duplicate first name and last name labels require using the id as the selector.
N/A
No.
=> Update test selectors

spec/features/edit_bulk_tags_spec.rb
This addresses some intermittent local failures by looking for NEW content first, with page reloads as necessary, and then looking for removed content to be gone.  It was running too quickly and the removed content wasn't gone soon enough.
=> edit_bulk_tags_spec: improve likelihood of passing

.rspec, .rubocop.yml, spec/features/access_indexing_spec.rb
To have an easy way to test the impact of the following on the Access Rights facet:
- cocina model access changes
- dor-services-app access mapping changes (from and to fedora)
- dor-indexing-app changes to use cocina model instead of fedora for indexing
- argo hook ins to cocina access as it affects indexing.
@andrewjbtw thought this was a good idea, btw.
tagging @mjgiarlo so he is aware of this.
Fixes #214 
.rspec was changed NOT to execute the new spec by default.
=> add temporary access_indexing spec that does NOT run by default

spec/features/create_preassembly_image_spec.rb
preassembly pulldown value changed with PR sul-dlss/pre-assembly/pull/758 and now our test will work again.
=> fix create_preassembly_image_spec 

README.md, config/settings.yml, spec/features/create_object_h2_spec.rb, spec/support/authentication_helpers.rb
These tweaks get the h2 test to work with the changes to authentication from PR #221, and get the hydrus test to work with the indexing changes in PR sul-dlss/dor_indexing_app/pull/580.
I was able to get each of the tests to run green in stage with these changes.
Part of fixing sul-dlss/infrastructure-integration-test/issues/219
FIxes #224 
Fixes #223
=> Fix h2 test

spec/features/create_apo_spec.rb
using the new apo form made some selectors no longer correct.
=> fix apo spec

.gitignore, spec/features/create_object_h2_spec.rb
H2 spec fails with currently deploying dependency updates due to link ambiguity in Argo...small change to fix this.
Also, update .gitignore so we don't mistakenly commit any manifest .csv files (even the file/media manifests)
=> fix h2 spec; ignore tmp .csv files

spec/features/create_object_no_files_spec.rb
Fixes #233
Adds opening and closing version to an existing test, to fulfill Andrew's request that this become a part of automated testing.
=> create_object_no_files_spec: add opening and closing version

spec/support/authentication_helpers.rb
It used to wait 60 seconds every time it checked to see if the login prompt was visible. There's no call for waiting that long.
=> Only wait one second to see if the password prompt is there.

config/settings.yml, spec/features/deposit_via_hydrus_spec.rb, spec/features/embargo_h2_spec.rb, spec/spec_helper.rb, spec/support/purl_helpers.rb
the Hydrus and H2 embargo specs weren't working consistently enough
=> fix embargo testing specs

spec/features/create_object_no_files_spec.rb
In some runs, the workflows was not being created. This will catch that problem.
NA
NA
=> Check that wf created for create_object_no_files spec.

spec/features/bulk_update_metadata_spec.rb
Test was failing due to slow upload.
Why is the upload slow? No idea.
=> Tweak to bulk_update_metadata spec to allow for slow upload.

spec/features/create_etd_spec.rb, spec/features/create_object_h2_spec.rb, spec/features/deposit_via_hydrus_spec.rb
After https://github.com/sul-dlss/argo/pull/2728 is merged, the text and selector of the embargo update form is slightly different.
=> Update selectors for new embargo modal

spec/features/access_indexing_spec.rb, spec/features/create_etd_spec.rb, spec/features/create_object_h2_spec.rb, spec/features/deposit_via_hydrus_spec.rb
_TLDR_:  "making the test use the search box was more reliable for me than having the test construct the search URL and visit it directly"
less handwavily...
I found that with the pattern of directly visiting the search URL, sometimes the browser running the specs would get hung up on the page it was navigating away from.  This was especially true when I was running `deposit_via_hydrus_spec.rb` and `create_object_h2_spec.rb` yesterday (as part of running the test suite for weekly dependency updates before deploying to prod).
I tested manually in my browser, and using the search field as this PR does leads to the same URL that the tests were constructing explicitly before this PR's change.
My hunch is that Capybara and the browser instance it uses get tripped up sometimes when a URL is …
=> Search more like human user

spec/features/create_apo_spec.rb
The previous value was not a valid license.
=> Update to use a valid license

spec/features/create_object_no_files_spec.rb
These will wait until the link or button is found and will not silently fail
=> Switch to capybara assertions

spec/support/page_helpers.rb
There's no sense in running the reindex if the text already exists on the page
=> Test for text before reindexing

README.md, config/settings.yml, config/settings/qa.yml, config/settings/staging.yml, spec/features/create_object_h2_spec.rb, spec/support/page_helpers.rb
52ffab5  - clarify the README and the settings.yml files re: token needed for both dor-services-app and dor-services-client
2d180df - fixes a race condition in the create_object_no_files test for less flappiness (yay!)
4133a17 - h2 test uses settings h2_purl_url so it works for both qa and stage.
yes, it was.
=> Improve 2 tests, clarify settings needs

spec/features/create_object_h2_spec.rb
The H2 integration test was failing due to a bad selector.  This fixes it.
Note: this test still fails in qa since there is no purl-qa.stanford.edu
=> fixes h2 integration test

Gemfile, Gemfile.lock, config/settings.yml, spec/features/create_preassembly_image_spec.rb, spec/spec_helper.rb, spec/support/event_helpers.rb, spec/support/page_helpers.rb
so that infra integration test suite can confirm that preservation and replication are working, since it's already implicitly exercised by accessioning.
closes #249
also, adds a (hopefully) generally useful helper method and pattern for querying the event service.
~~leaving in draft, as accessioning was wedged on stage when i tried to test last night (`provenanceMetadata` wasn't getting created, but i did test just this change by commenting out all of this class except the new event service check, and then hardcoding a known druid and version from stage -- obviously not a realistic enough test to merge this change).~~
n/a
nope
=> check event service to confirm preservation replicated new versions to all cloud endpoints

spec/features/create_object_h2_spec.rb
The page updates dynamically, so a reload is unnecessary
=> Remove an unnecessary reload

config/settings/qa.yml
So h2 test can pass in qa environment. 
n/a
n/a
=> correct settings/qa.yml for h2_purl_url

config/settings/qa.yml, config/settings/staging.yml
see discussion in slack, #dlss-infrastructure, week of 2021-06-21 and -06-28
n/a
nope, just configs in this app
=> http:// has been determined to be the canonical protocol for PURL

spec/features/create_object_h2_spec.rb
this test needed adjusting, because it couldn't find the field to add a depositor
n/a
n/a
=> adjust collection creation to work with sunet lookup change

config/settings/qa.yml, config/settings/staging.yml, spec/features/create_object_h2_spec.rb
1. PURL now uses https URLs
2. The terms checkbox for H2 is now conditional and will  not always appear - verify it exists before trying to check the box.
=> change purl url and fix terms checkbox

spec/support/page_helpers.rb
The `spec/features/sdr_deposit_spec.rb` started failing because the page in Argo never shows the object as completed accessioning, even though it had (as could be verified in another browser window).  This just forces the page to refresh even if a re-index was requested.
=> when re-indexing, still force a page refresh

spec/features/create_object_no_files_spec.rb
"close version" modal was reappearing when it shouldn't (using firefox).  There may be a better solution via the Argo code, but this gets the tests to pass.
=> fix broken create_object_no_files_spec

spec/features/create_etd_spec.rb
- Embargo date modal was re-appearing when it shouldn't (using firefox).  There may be a better solution via the Argo code, but this gets the tests to pass.
- avoid a ton of Faraday warnings by using their new syntax for authentication.
=> Fix broken create_etd_spec

README.md, config/settings.yml
- improve documentation on authentication configuration 
- reorder to have required configuration information before optional information
=> README: improve documentation on authentication configuration 

config/settings/qa.yml, config/settings/staging.yml, spec/features/create_object_h2_spec.rb
The name `h2_purl_url` threw me a bit. I can see that we only check the purl URL in the H2 test, but the name suggests that H2 has its own purl service to me. This commit changes that name to `purl_url`. FWIW, `purl_url` is a name we use elsewhere, like `shared_configs`, and I can't find any other usage of `h2_purl_url`.
Nope.
None for shared_configs, no.
=> Rename config variable to purl_url

spec/support/deposit_helpers.rb
```
$ bundle exec rspec ./spec/features/sdr_deposit_spec.rb
Run options: exclude {:indexing=>true}
Randomized with seed 17224
SDR deposit
deposits objects (FAILED - 1)
Failures:
1) SDR deposit deposits objects
Failure/Error: job_id = SdrClient::Deposit.run(kwargs)
ArgumentError:
wrong number of arguments (given 1, expected 0; required keywords: apo, source_id, url)
Finished in 14.93 seconds (files took 2.6 seconds to load)
1 example, 1 failure
```
=> Fix kwargs error.

.travis.yml
Put Travis's ruby version in sync with other projects, updating from 2.7 to 3.0. Not sure how to test this, although I know people have run infrastructure-integration tests with that Ruby 3.0. 
No
=> Update Travis Ruby version to 3.0

spec/features/create_virtual_object_spec.rb, spec/support/public_xml_helpers.rb
To test the other side of virtual object relationships (the constituent one).
=> Test that constituent public XML is as expected

.rspec, spec/features/access_indexing_spec.rb
Per discussion at meeting on Tuesday 2/22, we do not want any "optional" tests in this suite, so they stay current.
=> make access indexing test run by default

spec/support/page_helpers.rb
The old selector is no longer present in the new site design
=> Update how we check for workflow errors

spec/features/create_object_h2_spec.rb
This recent change (sul-dlss/argo#3132) requires updating the tests to open a version before changing embargo
Note: the re-index seems to be flaky for me (i.e. it sometimes does not show the reindex message making the test get hung up here: https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/support/page_helpers.rb#L24 which is called from here: https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_object_h2_spec.rb#L120-L121)
=> changing embargo now requires versioning

spec/support/deposit_helpers.rb
To allow the tests to run against cocina-models 0.68.0
n/a
=> Use cocina-models 0.68 namespace for object type URI

spec/features/edit_bulk_tags_spec.rb
Capybara needed more specific guidance on which of the renamed "Bulk Actions" links to click on or look for. Successfully ran on stage.
=> Specifying bulk actions text to click

spec/features/sdr_deposit_spec.rb, spec/support/page_helpers.rb
A couple of tests broke due to the newly added lazy loading of the Events and Technical Metadata sections (Argo view page).
In both cases, I discovered that even if the section is expanded, the content doesn't actually load till it scrolls into view.  Since the Capybara-controlled browser only scrolls far enough to get a clicked element into view, clicking these section headers doesn't actually scroll the content into view (the section header starts out below the end of the viewport, so clicking it puts only the section header into the viewport).
Sort of lucky that I figured it out -- was tipped off when I put my cursor into the Capybara-controlled browser's viewport to scroll down a bit and see what Capybara saw at the moment in the events section (since all the events seemed to be there …
=> update tests to handle Argo's lazily loaded sections

README.md, config/settings/qa.yml, config/settings/staging.yml
Ensure that Settings.preassembly_host includes stanford.edu so that scp
command works reliably with the ssh config in the README.md:
```
Host *.stanford.edu
GSSAPIDelegateCredentials yes
```
This will only delegate for the full hostname. I also fixed a typo and
provided a little bit more of a hint of where to find ETD
username/password.
Not needed!
=> Full host names

spec/features/create_preassembly_image_spec.rb
The preassembly image test failed a couple times because the PURL page didn't seem to be quite ready when it tried to visit it.  Refreshing the test browser allowed the test to continue and pass.  This will give us a second to wait for that PULR page and should make this test less flaky.  I am not sure why it's not ready when the status in Argo says it is accessioned (it should be).
=> wait for PURL page to be ready

spec/features/create_preassembly_image_spec.rb, spec/support/random_phrase_helpers.rb
We are hitting issues with the pre-assembly project name not being unique, which means there is a directory conflict.  This further randomizes the project name when running the test.
Ran it once on -stage successfully.
=> randomize pre-assembly project name more

spec/features/create_preassembly_image_spec.rb
The way content types are selected in the Argo registration form is changing (because of sul-dlss/argo#3548).  This fixes the tests because of this change.
=> [HOLD] update argo reg test for content type form update

spec/features/create_apo_spec.rb
This allows the APO feature spec to do its comparisons against text that is already on the Argo show page without having to compare against hidden data or expand sections that are lazy-loaded.
=> Prefer checking visible information to hidden information

spec/features/create_object_no_files_spec.rb
Because of this bug fixed here: https://github.com/sul-dlss/argo/pull/3654, tags were not making it through to object registration and it was not detected except by users.  This adds some checks to the integration tests to verify this bug will be caught if it occurs again.
(note: until that PR above is merged and deployed, this integration test will fail!)
=> add tag checks with object registration in argo

spec/features/create_apo_spec.rb
couldn't get the spec to get past `reload_page_until_timeout!(text: 'v1 Accessioned', with_reindex: true)` without it.  otherwise, the test would hang, and fail with e.g.:
```
Failures:
1) Use Argo to create an APO and verify new objects inherit its rights is expected not to have visible css ".alert-danger"
Failure/Error: click_link 'Reindex'
Selenium::WebDriver::Error::ElementNotInteractableError:
Element <a class="btn button btn-primary " href="/dor/reindex/druid:hn320cy6096"> could not be scrolled into view
```
n/a
=> fix create_apo_spec finding of Reindex button when waiting/reloading to look for 'v1 Accessioned' text

spec/features/create_preassembly_image_spec.rb
In the future, when assemblyWF switches to cocina, we will see the content earlier, but it will still be in progress, so some expected values won't show until assemblyWF has completed.
See https://github.com/sul-dlss/common-accessioning/pull/919
n/a
=> Just wait one time before examining the page

spec/features/create_object_h2_spec.rb
before this fix, `create_object_h2_spec.rb` consistently failed with `Capybara::Ambiguous:`  `Ambiguous match, found 2 elements matching visible button "Search" that is not disabled` on the parts of this spec that i modified.
after this fix, `create_object_h2_spec.rb` consistently passes.
There are multiple buttons on the page that contain the text "Search" (the other is the "Released to Searchworks" facet).  But the current locator for finding and filling in the search box still finds exactly one element, and pressing the Enter key in it after filling it in submits the search form successfully.
(Finding based on exact text would also be tricky: I noticed when debugging that the actual text of the search box submission button, from the perspective of Capybara::Node::Element#text is …
=> Press Enter key to submit search term

spec/features/create_preassembly_image_spec.rb
Because of https://github.com/sul-dlss/pre-assembly/pull/1012, we need to update our integration tests for pre-assembly.
Wait until that PR is merged
=> label change for pre-assembly

spec/features/create_preassembly_image_spec.rb
It was looking for argoxxx/view/druid:druid:bb666ss7777
=> fix create-image-preassembly-spec

spec/features/access_indexing_spec.rb, spec/features/create_apo_spec.rb, spec/features/create_object_no_files_spec.rb, spec/features/create_preassembly_image_spec.rb
After registering, bare druids are displayed instead of prefixed druids.
=> Updates specs for changes to druid after registering.

spec/features/access_indexing_spec.rb, spec/features/apo_creation_spec.rb, spec/features/bulk_tags_edit_spec.rb, spec/features/bulk_update_metadata_spec.rb, spec/features/collection_creation_spec.rb, spec/features/create_object_no_files_spec.rb, spec/features/etd_creation_spec.rb, spec/features/gis_accessioning_spec.rb, spec/features/goobi_accessioning_spec.rb, spec/features/h2_object_creation_spec.rb, spec/features/preasssembly_image_accessioning_spec.rb, spec/features/sdr_deposit_spec.rb, spec/features/virtual_object_creation_spec.rb, spec/features/web_archive_accessioning_spec.rb
So we don't have to fuss with cut and paste from the browser window for tests in progress.
Also updated a few spec descriptions
=> output druids for "when tests go bad"

spec/features/etd_creation_spec.rb
Fake etd approvals need to happen more than 1 second after submission for them to stick
See https://github.com/sul-dlss/hydra_etd/blob/main/app/services/registrar_data_importer.rb#L150-L160 
If submission and update are too close together, this logic can sometimes return false, causing the faked approval/updates to not be saved.
=> Fix ETD Flaky Spec

spec/spec_helper.rb
These two settings are needed (for some) to not be barraged with confirmation dialogs about the certificate from Cardinal Key:
- `security.enterprise_roots.enabled` set to `true`
- `security.default_personal_cert` set to `Select Automatically`
See: https://uit.stanford.edu/service/cardinalkey/known-issues
No.
=> Configure for Cardinal Key

spec/support/authentication_helpers.rb
This is a new step, apparently. Also, the nearby sleep appears no longer to be needed. Leaving commented out in case someone else runs into auth issues in the near future, as a clue for them to follow.
no
=> Update authentication to add brower trust button step

spec/features/h2_object_creation_spec.rb
It is safer to do an exact match search in Argo for the test H2 objects we are creating in the tests, or else we might get two results, confusing the test selectors.
e.g. https://argo-qa.stanford.edu/catalog?search_field=text&q=SUL+Logo+for+Balti+Stir+Fry+Mix+Cornichons
=> do an exact match for titles of test objects

spec/features/h2_object_creation_spec.rb
1. Set a specific "wait" time of 0 when checking that an element is not on the page (else we wait for a long time even though it was never there and never will be).
2. There appears to be a race condition in the accessionWF#shelve step.  I don't fully understand it, but this step makes a single call to dor-services-app, which then starts a job, which then uses `ShelvingService` in dor-services-app, which does some content diffing and copying and expects files to be available in preservation.  The theory is that If we create a V2 immediately after accessioning a V1, perhaps preservation needs a few more seconds to catch up and show the files as available.  It always fails for me with no sleep (and I can get it to continue by manually reseting the step in a separate browser).  Putting a …
=> address some issues with H2 test flakiness

README.md, config/settings.yml, spec/features/access_indexing_spec.rb, spec/features/apo_creation_spec.rb, spec/features/collection_creation_spec.rb, spec/features/create_object_no_files_spec.rb, spec/features/etd_creation_spec.rb, spec/features/gis_accessioning_spec.rb, spec/features/goobi_accessioning_spec.rb, spec/features/h2_object_creation_spec.rb, spec/features/preassembly_image_accessioning_spec.rb, spec/features/sdr_deposit_spec.rb, spec/features/virtual_object_creation_spec.rb, spec/features/web_archive_accessioning_spec.rb, spec/support/authentication_helpers.rb, spec/support/deposit_helpers.rb, spec/support/page_helpers.rb
See above. Changes included:
* Remove `with_reindex` arg from reload_page_until_timeout helper
* I added this ability a long time ago when indexing Fedora changes into Solr took more time, but I suspected it was no longer necessary and causes more clicks and uses more resources than is necessary. Upon removing this ability, I found that the test runtime is more or less unaffected.
* Move post-authentication timeout into configuration block
* This commit moves a stray timeout into a block of similar timeouts in the application config. This keeps the configuration organized and consistent, making it easier to see all overrideable timeouts at a glance.
* Speed up and robustify ETD creation spec
* This commit contains a number of changes related to improving the reliability and runtime speed …
=> Make the tests faster, more reliable, and easier to extend

spec/features/etd_creation_spec.rb, spec/features/h2_object_creation_spec.rb, spec/support/authentication_helpers.rb
this rebases my branch from #521 on @mjgiarlo's branch from #517, and rebases it all on current `main`.  some of my changes from #521 evaporate out.
happy to let #517 get merged, and then rebase this.
* typo fix
* slightly more modular prompting for username/password as needed (and if prompting for username, does so before browser launch)
* re-enables check for embargo date, with a bit more looser of a date expectation
a bit more detail in commit messages.
N/A, i think?
=> authentication fixups, ETD embargo date check

spec/features/h2_object_creation_spec.rb
Since the upload is no longer selected by default it needs to be clicked before `Choose files` appears on the page. Maybe there's a better way of getting capybara to find the radio button?
=> Click upload

spec/spec_helper.rb
Rather than as "capabilities," which are now deprecated. This change removes deprecation warnings without affecting test behavior.
No
=> Pass Selenium driver options as options

spec/features/virtual_object_creation_spec.rb, spec/support/deposit_helpers.rb
Connects to sul-dlss/argo#3945
This commit adds a viewing direction to the object used as the virtual object in the virtual object creation test, in order to make sure objects with an existing member order are correctly virtual object-ified.
=> Test virtual object creation with an item containing a member order

README.md, config/settings.yml, config/settings/qa.yml, spec/features/create_folio_object_spec.rb, spec/features/sdr_deposit_spec.rb
Fixes #561 
Add a new spec to verify we can register objects in Argo using a folio_instance_hrid and it pulls the label from Folio.
Note: This will only work if the environment being tested has folio enabled across all apps.  This is currently only true in QA.  This is determined via the setting.
Yes
=> add new spec for registering objects with folio_instance_hrid

spec/features/create_folio_object_spec.rb
If no SDR_ENV is passed, we need this so it defaults to stage as in other test.
Follow on from #565
=> default to stage if no SDR_ENV

spec/features/etd_creation_spec.rb
Closes #571 ... but doesn't implement it.
Turns out I was wrong -- it is NOT easy to fake the rest of the etdSubmitWF steps, even with Folio.  I changed the comment to clarify that.
=> etd test can't finish etdSubmitWF steps 

spec/features/h2_object_creation_spec.rb
h2_object_creation test kept failing for me for two reasons:
1.  the current_url it was parsing for the druid was the search url, not the show url for an object.  This is a fix for the problem.
2. it gets hung up on the shelve step because the content isn't in the right place yet.  For that I was manually rerunning the shelve step in another window.  Sidekiq can't do it because it ran the job and it failed.   I did not fix that problem.
=> h2_object_creation: current_url is sometimes slow

config/settings.yml
goobi stage was rebuilt to use ubuntu as its OS, and now lives at a slightly different hostname
n/a
=> update Settings.goobi.url to point to newly built goobi stage server

spec/features/web_archive_accessioning_spec.rb
Connects to sul-dlss/was_robot_suite#583
`Tempfile.new` defaults to 0600 permissions (user r/w) and this breaks the web archive accessioning spec when we deploy presbots with the tarpipe-to-cp change. This commit lets the test pass with that new code deployed.
=> Change permissions of manually created WARC file

spec/features/preassembly_hfs_accessioning_spec.rb, spec/features/preassembly_image_accessioning_spec.rb
To help the pre-assembly tests pass in stage. They were consistently failing with the prior sleep values, now that Ruby 3.2 is deployed everywhere. They were the only tests that failed.
I'm not sure how much to be concerned about this, given that Andrew's testing in stage has not reproduced this error condition. He's tried with a batch of small files and a batch of large files, and neither wound up in this situation.
No.
=> Bump sleeps in pre-assembly specs to allow them to pass

Gemfile, Gemfile.lock
I couldn't run the integration tests when I upgraded to ruby 3.2.2;  they failed with this error:
```
$ bx rspec
An error occurred while loading spec_helper. - Did you mean?
rspec ./spec/spec_helper.rb
Failure/Error: require 'selenium-webdriver'
LoadError:
cannot load such file -- websocket
```
I could run rspec with ruby 3.1.2, but not with ruby 3.2.2.   when I added the `websocket` gem on the command line for ruby 3.2.2, I could run rspec with ruby 3.2.2.   Hence, my adding it to the Gemfile.  It may or may not fix the problem for the next person upgrading to ruby 3.2.2.
I also note https://github.com/titusfortner/webdrivers/blob/main/README.md?plain=1#L8-L12, which may imply we won't need the webdrivers gem much longer (?)  ... which is not to say we wouldn't need websockets.
=> explicitly add websocket as a gem

spec/features/item_creation_with_folio_hrid_spec.rb
looks like the relevant argo change was made here: https://github.com/sul-dlss/argo/commit/36bacbe475d45f73c791816d20ffbf6578e08352
keep the test suite up to date.  discovered when running against QA after deploying this week's dep updates.
nope
=> fix label text used to find Metadata Source facet button in test for Argo item creation with folio HRID

spec/support/authentication_helpers.rb
Fixes #604 
Clicks this automagically:
no need
=> authentication clicks through 'Yes, this is my device'

spec/features/etd_creation_spec.rb
to decouple comment language from symphony
it wasn't necessary.
=> adding comments pertaining to folio cutover

spec/features/preassembly_hfs_accessioning_spec.rb, spec/features/preassembly_image_accessioning_spec.rb
Because changes in sul-dlss/pre-assembly#1180 change the UI and we need to update the integration test to match.
~~HOLD until pre-assembly change is merged~~
=> update integration tests for pre-assembly changes

README.md, config/settings/qa.yml
=> Remove transitional README block now that we are on folio

spec/features/preassembly_reaccessioning_spec.rb
Getting to the point where it was possible to have collisions in the name of the preassembly project dir created for integration tests. 
N/A
=> More randomness in preassembly staging dirs

README.md
People should look directly in vault rather than shared configs for the Goobi and hydra_etd credentials.
lol
=> Add vault instructions

spec/features/bulk_tags_edit_spec.rb
`exploded_tag_ssim` is going away in PR sul-dlss/dor_indexing_app/issues/1025
Ran this updated test against stage and it passed.
=> bulk_tags_edit_spec: update tag field

.rubocop.yml, spec/features/access_indexing_spec.rb, spec/features/apo_creation_spec.rb, spec/features/etd_creation_spec.rb, spec/features/gis_accessioning_spec.rb, spec/features/goobi_accessioning_spec.rb, spec/features/h2_object_creation_spec.rb, spec/features/item_creation_no_files_or_collection_spec.rb, spec/features/item_creation_with_folio_hrid_spec.rb, spec/features/preassembly_hfs_accessioning_spec.rb, spec/features/preassembly_reaccessioning_spec.rb, spec/features/web_archive_accessioning_spec.rb
The former is ambiguous for argo object registration and search.
I like the spirit of the rubocop suggestion, but for an integration test of other existing codebases, it seems a bit presumptuous.  So, I went with inline exceptions and a comment, since it might be nice to have rubocop nudge us towards better page element disambiguation when writing new app code (which seems like the driver for most, though not all, of our new integration tests?).  But I'm totally happy to just disable the rubocop rule with an explanation in `.rubocop.yml`, and get rid of the inline comments and exceptions.
Also, for the cases that make a difference in Argo, I'm guessing that this isn't a huge deal: I doubt that sighted users will confuse the "Register" nav link at the top of the page with the "Register" …
=> revert some click_link_or_button changes back to click_button

spec/spec_helper.rb
This commit does not make any functional changes since the sdr-client gem allows requires of both, at the moment at the least. Ran the SDR deposit spec to confirm.
N/A
=> Prefer current `sdr_client` require to outdated `sdr-client` one

config/settings.yml, spec/features/h2_globus_creation_spec.rb, spec/features/h2_object_creation_spec.rb, spec/support/h2_helpers.rb
I was getting presented with a terms of deposit modal in the H2 tests modified here, and since the tests didn't handle it, I had to babysit them and click through manually to get them to pass.  This PR should hopefully alleviate the babysitting.
_**Example of the modal:**_
Here's an example screencast of me successfully letting the two modified tests run.  It's a bit long, but you can see the terms modal flit by at 0:10 and 0:25 for one test; and 1:04 and 1:46 for the other.  It was 65 MB over github's 100 MB limit, hence this drive link: https://drive.google.com/file/d/1n2EOWYXZykIJJZ2x1FoydiivouSQyNiv/view?usp=drive_link
_**screenshot of the test output:**_
=> H2: click through the terms of deposit modal when it's presented

spec/features/gis_accessioning_spec.rb
Test assumes that gisDeliveryWF starts automatically at the end of gisAssemblyWF.
N/A
=> Remove manual start of gisDeliveryWf

spec/features/gis_accessioning_spec.rb
We do not need this manual completion anymore now that https://github.com/sul-dlss/gis-robot-suite/issues/401 is fixed
See https://github.com/sul-dlss/workflow-server-rails/pull/707
Tested with this fixed deployed to stage
Nope
=> remove unnecessary code now that bug is fixed

spec/features/gis_accessioning_spec.rb
We should consider selecting 'geo' as the content type when registering the object in Argo for the geo integration test.  Currently it works fine selecting 'file' as a later step in the process will switch it to geo, but we believe the only reason this was necessary was because geo was not always an option when registering in Argo.  It is now, and seems less confusing to just select that from the beginning.
Tested on stage and the test still works.
=> select geo for geo integration spec

spec/features/gis_accessioning_spec.rb
Tests that accessionWF is kicked off from gisDeliveryWF. 
N/A
=> Remove manual start of accessionWF for gis test

spec/features/gis_accessioning_spec.rb
test was failing because it takes a long time to assert that text is NOT on a page.  It passed with this change (after failing 3 times) and it also passed a LOT faster.
=> gis test: look for desired text

spec/features/gis_accessioning_spec.rb
Checks for XML metadata being shelved as in https://github.com/sul-dlss/gis-robot-suite/pull/773.
=> [HOLD] Check for shelved GIS XML metadata

spec/features/preassembly_gis_accessioning_spec.rb
follow-on to https://github.com/sul-dlss/infrastructure-integration-test/pull/684/
implements same expectation update as `spec/features/gis_accessioning_spec.rb`, but in `preassembly_gis_accessioning_spec.rb`
=> Check for shelved GIS XML metadata

spec/features/gis_accessioning_spec.rb
We are no longer creating and shelving data.zip file. So the test needs
to be adjusted to not look for it.
See: https://github.com/sul-dlss/gis-robot-suite/issues/753
=> No more data.zip

spec/features/preassembly_gis_accessioning_spec.rb
Here's another integration test that was expecting GIS items to get a data.zip. See https://github.com/sul-dlss/gis-robot-suite/issues/753
=> No more data.zip (again)

config/settings.yml, config/settings/stage.yml, spec/features/gis_accessioning_spec.rb, spec/features/preassembly_gis_accessioning_spec.rb
Fixes #640 - ensure GIS items make it to Earthworks after release.  The tests already verify the PURL is there, so no additional work required for that.
Tested with main deployed to stage.
=> verify gis objects make it to Earthworks

spec/features/gis_accessioning_spec.rb
Updated intetgration test to go with:
https://github.com/sul-dlss/gis-robot-suite/pull/834
https://github.com/sul-dlss/workflow-server-rails/pull/729
https://github.com/sul-dlss/pre-assembly/pull/1412
Example: https://argo-stage.stanford.edu/view/druid:rw641dn6622
=> Update gis_accessioning for druid tree path structure

config/settings.yml, spec/features/goobi_accessioning_spec.rb
purl-stage is pointing at SearchWorks-preview-stage, not prod. This allow the Goobi test to pass as of 3/4/24.
=> Change the default SearchWorks URL

spec/features/preassembly_reaccessioning_spec.rb
~~HOLD for Part 1 of sul-dlss/technical-metadata-service/issues/510~~
This is part 1A of [sul-dlss/technical-metadata-service/issues/510 
](https://github.com/sul-dlss/technical-metadata-service/issues/510#issuecomment-1959971140)
and will require Part 1 to be addressed.
We want to be sure that there is technical metadata for all files in the object, even if files aren't included in targeted file update as a reaccession.
=> preassembly-reaccession: add test for technical metadata

README.md, config/settings.yml, spec/features/gis_accessioning_spec.rb, spec/features/preassembly_gis_raster_accessioning_spec.rb, spec/features/preassembly_gis_vector_accessioning_spec.rb, spec/features/preassembly_hfs_accessioning_spec.rb, spec/features/preassembly_reaccessioning_spec.rb, spec/features/web_archive_accessioning_spec.rb
Doing so allows us to use a more sophisticated setup using SSH multiplexing, holding a connection open for a short period of time to reduce the overall number of MFA pushes. This change depends on all of us devs having some common SSH config which will be shared and documented elsewhere.
Blocked by https://github.com/sul-dlss/DeveloperPlaybook/pull/230
=> Prefer setting SSH ProxyJump in config over command-line options

spec/features/item_creation_no_files_or_collection_spec.rb
One should not start accessioningWF on an open version.  Tested this on qa and stage.
fixes #717
=> Close a version to initiate accessioningWF

config/settings.yml, config/settings/qa.yml, config/settings/stage.yml, spec/features/preassembly_gis_raster_accessioning_spec.rb, spec/features/preassembly_gis_vector_accessioning_spec.rb, spec/features/preassembly_hfs_accessioning_spec.rb, spec/features/preassembly_ocr_document_spec.rb, spec/features/preassembly_ocr_image_spec.rb, spec/features/preassembly_ocr_spec.rb, spec/features/preassembly_reaccessioning_spec.rb
Fixes #730 
Follow on work described in #741
This adds a new integration test to run pre-assembly for an image object and a document object which starts OCR.
It is useful during testing to let us run objects through ocrWF.
Still to do:
=> OCR Image/Document Spec

spec/features/preassembly_ocr_image_spec.rb
The size of the generated OCR XML is slightly bigger now.
Nope.
=> generated ocr xml is a bit bigger now

spec/features/preassembly_ocr_image_spec.rb
Because of https://github.com/sul-dlss/common-accessioning/pull/1286 which changes some logic with OCR
=> ocr txt files do not have transcription role set

spec/features/preassembly_ocr_document_spec.rb, spec/features/preassembly_ocr_image_spec.rb
1. Adjusts expectations to match reality (number of files)
2. Put PURL expectations last, so we don't have to go back to Argo again later (we were already there before)
=> adjust expectations and avoid back and forth to argo

Gemfile, Gemfile.lock, spec/spec_helper.rb
This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
=> Add csv dependency to bundler

spec/spec_helper.rb
Add `require 'csv'` in the places that we open a CSV now that the gem is explicitly included.
=> Add require csv where necessary

spec/features/preassembly_ocr_document_spec.rb, spec/features/preassembly_ocr_image_spec.rb
When running on stage, the OCR accessioning produced slightly different file sizes for XML and TXT.
=> relax expectations for ocr specs

spec/features/h2_versioned_object_creation_spec.rb
Goes with https://github.com/sul-dlss/happy-heron/pull/3598 which updates the versioned purl links to use `/version/N`
=> Use new purl version pattern

spec/features/preassembly_gis_raster_accessioning_spec.rb, spec/features/preassembly_gis_vector_accessioning_spec.rb
"Scale not given" was removed in https://github.com/sul-dlss/mods_display/pull/180
=> Remove scale not given from gis test as it's no longer produced

config/settings.yml, spec/support/capybara.rb
I needed it to deal with how Firefox is being shipped in modern Ubuntu versions. I don't think it'll break anyone else since it's opt-in, but it may be good to verify that.
No.
=> Allow configuration of firefox/geckodriver paths and disable pop-up download panel

spec/features/preassembly_ocr_image_spec.rb, spec/support/page_helpers.rb
this accounts for a race condition where fetch-files fails to get the files on the first try or 3, because there seems to occasionally be some lag before the files are available for read by the preservation_catalog web VMs.  previously, the spec failed on line 119 due to the workflow error.
plus an opportunistic YARD typo fix.
example of successful accessioning after manually retrying (this just has the test do the same automatically).
note: i think this is ok, and is something we've seen intermittently on stage and not worried about, including with ocrWF, but i'm not 100% sure about that.  if it feels like this is papering over a serious problem, we can work with ops to investigate the lag (probably a good idea even if this fix is also a good idea, and could reproduce using the code from …
=> retry ocrWF fetch-files if preservation-client retrieval errors

spec/features/preassembly_ocr_image_spec.rb
Reverts sul-dlss/infrastructure-integration-test#795
may be unnecessary.  try restoring retry behavior in the common-accessioning robot, see https://github.com/sul-dlss/infrastructure-integration-test/pull/795#issuecomment-2458141891
see https://github.com/sul-dlss/common-accessioning/pull/1421 for testing info.
part of https://github.com/sul-dlss/common-accessioning/issues/1420
=> Revert "retry ocrWF fetch-files if preservation-client retrieval errors"

spec/features/preassembly_speech_to_text_media_spec.rb
Goes with https://github.com/sul-dlss/common-accessioning/pull/1431
This updates the media test to handle the json files being part of the object
=> preserve json files for stt

spec/features/preassembly_speech_to_text_media_spec.rb
Goes with https://github.com/sul-dlss/common-accessioning/pull/1449 to account for differing filenames now in the captioning process
Hold until the common accessioning PR is merged
=> update speech to text test to match new filenames

spec/spec_helper.rb
need to explicitly require csv when running on ruby 3.4 or later (csv gem is already included in gemfile)
=> require csv for ruby 3.4.1

spec/features/sdr_deposit_spec.rb, spec/spec_helper.rb, spec/support/download_helpers.rb
file system lag (?) made `sdr_deposit_spec` almost unusable for me otherwise this week.
since the console output prints the info about the screenshot fairly prominently, and since the screenshotting isn't configurable in this version of the PR, it didn't seem necessary to adjust the readme.  but i'm of course happy to add to the readme for this PR as-is if that's desired, and/or to make the screenshotting behavior configurable (e.g. enabled via setting, with whatever default people prefer).
=> Error handling improvements

Gemfile, Gemfile.lock, spec/spec_helper.rb
This is a small housekeeping PR that resolves the deprecation warning below related to `byebug` and we mostly use `debug` throughout our repos now.
```
/Users/amcollie/.rbenv/versions/3.4.1/lib/ruby/3.4.0/readline.rb:4: warning: reline was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add reline to your Gemfile or gemspec to silence this warning.
/Users/amcollie/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/byebug-11.1.3/lib/byebug/commands/irb.rb:4: warning: irb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add irb to your Gemfile or gemspec to silence this warning.
```
=> Switch to debug to follow our standard practices moving away from byebug

spec/features/sdr_deposit_spec.rb
before adding this hack, `sdr_deposit_spec.rb` was failing for me very consistently this afternoon, as follows:
```
Failures:
1) SDR deposit deposits objects
Failure/Error: expect(file_listing.size).to eq 2
expected: 2
got: 1
(compared using ==)
```
and in watching the automated browser, or looking at the failure screenshot, i could indeed see only one file listed in the section.  but every time i visited the page for the test druid myself, even if i did it before the spec got to the aforementioned failing test, i'd see two files.  i could `sleep(60)` before opening the techMD section, and there's already a check before that section is opened to ensure status is `v1 Accessioned`.  that's all to say, i don't think this one is lag in the service, i think it's a quirk of the …
=> tiny hack to presumably give time for all the expected page elements to render before looking for them, to avoid potentially undercounting

spec/features/h3_object_creation_spec.rb, spec/features/item_creation_no_files_or_collection_spec.rb, spec/support/page_helpers.rb
More reliable integration tests that need slightly less nudging and babysitting.  See below for example error addressed by this PR.
To test, I re-ran the whole suite.  I still had to re-run a number of failed tests individually.  But without the changes in this PR, I also had to babysit and use another browser to manually retry the workflow steps that this PR auto-retries. (I still had to do that occasionally for a couple H2 specs, but I figured those would be retired soon, and so didn't bother fixing them up)
I assume the first commit won't be that controversial.
The second commit adds a mechanism for workflow step retry that is more flexible than current `main`, and backwards compatible with existing usage.  It also feels a little weird and hacky, esp with the return type examination. …
=> Workflow retry hijinks

spec/features/goobi_accessioning_spec.rb, spec/features/preassembly_ocr_image_spec.rb, spec/features/preassembly_reaccessioning_spec.rb
We started getting errors when trying to access the canvas id URL in IIIF manifests. This is no longer intended to be resolvable, so we should just check the image URL works.
=> Only check image URL not canvas id in IIIF manifest

spec/features/gis_accessioning_spec.rb, spec/features/preassembly_gis_raster_accessioning_spec.rb, spec/features/preassembly_gis_vector_accessioning_spec.rb
There are several tests (all GIS accessioning) which are looking for specific metadata on the PURL page.  This PR changes the test to look for the expected values in the cocina JSON, rather than the PURL page, since changes in display logic may break the test and are tested elsewhere (e.g. cocina_display).
=> Use cocina JSON when testing GIS publishing to PURL

config/settings.yml, spec/features/virtual_object_creation_spec.rb
Resolves #757 by using Preassembly instead of sdr_client to deposit works for a virtual object. This is more typical of how users create virtual objects and will ensure the test object virtual object constituents can be successfully viewed on PURL.
=> Use Preassembly in virtual object test
