- spec/features/create_apo_spec.rb
Fixes #4
I can confirm all three specs complete successfully.
> Add an integration test to create an APO via Argo

- spec/features/create_object_no_files_spec.rb
Feature runs through process of registering and accessioning an object with no files. 
Closes: #6
> Feature for creating an object without files

- spec/features/create_etd_spec.rb
incorporating one last suggestion from PR #37 comments
na
> create_etd_spec: remove unnec "page."

- spec/features/create_etd_spec.rb
- spec/support/etd_helpers.rb
Improve readability of the test.
n/a
> More tweaks to the etd spec

- spec/features/sdr_deposit_spec.rb
> Add techmd check

- .rubocop_todo.yml
- spec/features/create_media_objects_spec.rb
- spec/features/deposit_via_hydrus_spec.rb
Reduce the amount of style exceptions in the TODO.
no
> Autocorrect Style/IfUnlessModifier

- README.md
To clarify how we can get tests to run.
Yes.
> Update README to make prerequisites clear

- spec/features/create_media_objects_spec.rb
- spec/features/create_preassembly_image_spec.rb
- spec/features/reaccession_via_preassembly_spec.rb
Per Andrew's request to have an integration test for an image object run through preassembly.
Closes #23 
na
> Image preassembly test

- spec/features/create_media_objects_spec.rb
I introduced a bug in this test;  this fixes it.
na
> fix create_media_objects_spec

- spec/features/bulk_update_metadata_spec.rb
- spec/features/create_collection_spec.rb
- spec/features/sdr_deposit_spec.rb
- spec/support/constants.rb
- spec/support/xlsx_helpers.rb
This will make it easier to reset the test suite if we ever clear stage.
no
> Extract APO to a constant

- Gemfile
- Gemfile.lock
- spec/features/bulk_update_metadata_spec.rb
- spec/features/sdr_deposit_spec.rb
- spec/support/authentication_helpers.rb
- spec/support/constants.rb
- spec/support/xlsx_helpers.rb
Use the API for doing registration.
no
> Upgrade to sdr_client 0.22.0

- spec/features/bulk_update_metadata_spec.rb
Easier to read, and less fragile.  
Tested by running the tests. 🤷
> Use capybara methods

- spec/features/bulk_update_metadata_spec.rb
Depends on https://github.com/sul-dlss/argo/pull/2052
This is easier to read.
ran the tests.
none
> Use the capybara attach_file method

- .github/pull_request_template.md
This repo is a test.  Typically we don't test our tests.
It wasn't
none
> Remove questions that don't make sense in this repo.

- spec/features/sdr_deposit_spec.rb
To account for async deposit (requiring checking status).
No
No
> Adds status checking to sdr deposit spec.

- spec/features/create_object_no_files_spec.rb
Cleaner test, consistent useage of capybara
n/a
no
> remove unnecessary "page."

- spec/features/edit_bulk_tags_spec.rb
Test was failing because underlying markup changed
n/a
no
> Fix bulk tag spec for argo on blacklight 7

- settings.yml
- spec/features/deposit_via_hydrus_spec.rb
- spec/features/edit_bulk_tags_spec.rb
- spec/spec_helper.rb
Connects to sul-dlss/argo#2163
I ran this test and can affirm that is passes. I believe @aaron-collier also successfully ran the test.
> Test bulk tags as an Argo bulk action not a bulk update

- spec/features/create_etd_spec.rb
Fixes #125 
To fix spec broken by markup change to improve accessibility.
na
na
> fix etd spec

- README.md
@ndushay asked a question about the README in my last PR, so here we are.
Yees
No
> Reorganize README a bit

- Gemfile.lock
Fixes the tests that call `SdrClient::Deposit.run`
> Update sdr-client to use new version of cocina-models

- spec/features/create_apo_spec.rb
- spec/features/create_collection_spec.rb
- spec/features/create_object_no_files_spec.rb
- spec/features/create_preassembly_image_spec.rb
- spec/features/sdr_deposit_spec.rb
- spec/spec_helper.rb
- spec/support/page_helpers.rb
To speed up the build.
No.
No.
> Speed up the build

- config/settings/qa.yml
- config/settings/staging.yml
- spec/features/create_object_h2_spec.rb
Fixes https://github.com/sul-dlss/happy-heron/issues/203
n/a
n/a
> Tests adding a Collection and Work in H2

- spec/features/create_object_h2_spec.rb
> Updates spec to use latest H2 stage release

- .rubocop.yml
- spec/features/create_object_h2_spec.rb
- spec/support/authentication_helpers.rb
h2 show page changes required changes to the h2 spec
n/a
> create_object_h2 fix due to show page changes

- Gemfile
- Gemfile.lock
to keep in sync with tiny cocina-models change for a dor-services-app mapping ticket.
> update sdr-client to 0.39.0

- spec/features/create_etd_spec.rb
- spec/features/create_object_h2_spec.rb
- spec/spec_helper.rb
I ran all the specs and now they all pass.
> Fix ETD and H2 specs so they pass

- README.md
Changes master to main branch in README
Yes
no
> Branch change in README

- Gemfile
- Gemfile.lock
> Update to sdr-client 0.41.0

- .rubocop.yml
- spec/features/create_object_h2_spec.rb
turbo-frame changes broke the h2 integration test;  this fixes it.
> fix h2 integration test

- spec/features/create_object_h2_spec.rb
> Update integration test for h2 now that it does a live update

- spec/features/create_object_h2_spec.rb
- spec/support/authentication_helpers.rb
This prompt asks if you want to work on your draft, which takes you away from the path we are trying to test.
> Dismiss the prompt for h2

- spec/features/create_object_h2_spec.rb
Green is my favorite color.
NA
NA
> Fix for H2 spec.

- .gitignore
stumbled on this out of date comment and exclusion
n/a
n/a
> fix out of date comment and exclusion

- spec/support/authentication_helpers.rb
I was running an integration test and it was failing as soon as I approved in Duo.  Apparently some of our systems (or maybe all???) do automatic duo pushes now.
> authentication allows for automatic duo pushes

- Gemfile.lock
Use the latest models and gems.
No
No
> Bump cocina models and related gems

- spec/features/create_apo_spec.rb
> Test the forms accessibility by using labels rather than selectors

- spec/features/embargo_h2_spec.rb
- spec/features/embargo_hydrus_spec.rb
fixed the h2 embargo spec so it should pass when DSA is correct.
> fix embargo specs

- spec/features/create_etd_spec.rb
Less bashing of head against desk.
NA
NA
> Tweak to create_etd_spec.

- spec/features/deposit_via_hydrus_spec.rb
Connects to sul-dlss/hydrus#478
> Test collection rights in Hydrus

- spec/features/create_object_h2_spec.rb
> Update h2 spec to follow new UI changes

- Gemfile.lock
> Update dor-services-client and sdr-client (for cocina-models 0.60.0)

- spec/features/create_object_h2_spec.rb
> Adds H2 test for new version.

- spec/features/access_indexing_spec.rb
- spec/features/create_etd_spec.rb
- spec/features/create_object_h2_spec.rb
> Use idiomatic capybara commands

- Gemfile
- Gemfile.lock
> Update cocina-models to 0.61.0 

- .rspec
- spec/features/create_apo_spec.rb
- spec/features/create_preassembly_image_spec.rb
- spec/support/page_helpers.rb
- use documentation format so it's easier to see which test it's running when you're running all of them.
- use shorter syntax to refresh the page in page_helper
- Fix typos
> Small improvements

- spec/features/create_object_h2_spec.rb
> Adds PURL registration to H2 test.

- spec/features/create_object_h2_spec.rb
h2 spec never succeeded due to introduced error
> Fix h2 spec

- spec/features/create_collection_spec.rb
This implementation is subject to change (indeed it has), and such details shouldn't be in an integration spec
> Remove implementation detail from feature spec

- Gemfile.lock
to update dependencies (wasn't triggered by jenkins for some reason)
> Update dependencies (manually)

- config/settings.yml
- spec/spec_helper.rb
- spec/support/config.rb
> Remove deprecated usage and be kind to the user

- spec/features/bulk_update_metadata_spec.rb
> Update selector for argo bulk table

- spec/features/bulk_update_metadata_spec.rb
- spec/features/create_preassembly_image_spec.rb
- spec/features/sdr_deposit_spec.rb
- spec/support/page_helpers.rb
Update tests to use new selectors related to ongoing changes in Argo.
> Fix integration tests effected by UI changes

- Gemfile
- Gemfile.lock
- README.md
- config/settings.yml
- spec/features/create_virtual_object_spec.rb
- spec/support/config.rb
- spec/support/deposit_helpers.rb
Resolves #112 to create a virtual object with multiple constituents via Bulk Action. 
[Example virtual object with 2 constituents](https://argo-stage.stanford.edu/view/druid:hy591qz5434). (3:59 to run)
[Example virtual object with 11 constituents](https://argo-stage.stanford.edu/view/druid:mr596mj1416). (14:08 to run)
Is 14 minutes a reasonable amount of time to have a test take? The number of constituents is set in a let definition--I can see how long it takes with other numbers of constituents if that's useful. 
No further set-up or configuration needed for this test.
> Virtual objects integration test

- spec/features/create_virtual_object_spec.rb
One of the druid variables needed its naming updated for the test to run.
> Update to variable name.

- spec/features/access_indexing_spec.rb
- spec/features/bulk_update_metadata_spec.rb
- spec/features/create_apo_spec.rb
- spec/features/create_collection_spec.rb
- spec/features/create_etd_spec.rb
- spec/features/create_object_h2_spec.rb
- spec/features/create_object_no_files_spec.rb
- spec/features/create_preassembly_image_spec.rb
- spec/spec_helper.rb
- spec/support/table_helpers.rb
To get the integration tests passing with the large batch of major Argo UI changes we are in the process of making.
> Reflect Argo UI changes in tests

- .github/pull_request_template.md
Good pull request explanations save lives.
> Update pull request  template

- spec/features/create_apo_spec.rb
- spec/features/create_object_h2_spec.rb
- spec/features/create_virtual_object_spec.rb
> Test tweaks.

- spec/features/bulk_update_metadata_spec.rb
https://github.com/sul-dlss/argo/pull/3175
> Update test for argo after change to the UI

- spec/features/create_preassembly_image_spec.rb
Tested in QA and stage and both pass.
Fixes #362
This commit adds a few tests to the preassembly spec (already accessions an object w/ an image) to make sure we are shipping legit content metadata to PURL. We test that by exercising the IIIF manifest, validating it as JSON, and reaching into the manifest to ensure it returns a real JPEG image.
No
> Test functional IIIF in Purl

- spec/features/create_etd_spec.rb
Faraday auth config changed in v2.
> Fix faraday config for ETD spec.

- spec/features/create_virtual_object_spec.rb
- spec/features/edit_bulk_tags_spec.rb
> Fix for Argo UI changes related to bulk actions.

- Gemfile.lock
- spec/features/sdr_deposit_spec.rb
To keep pace with cocina-models and client releases, and fix a now-broken test.
No
> Bump clients and change access to view

- config/settings/qa.yml
- config/settings/staging.yml
So the tests can pass now that DSA is load-balanced in QA and stage.
No
> Change dor-services-app URLs to load-balanced endpoints

- spec/support/deposit_helpers.rb
Access is now view. This fixes the build. Ran against QA and they all pass now.
No
> Make deposit helper method invoke sdr-client with changed cocina ACL keyword

- Gemfile
- Gemfile.lock
- spec/features/access_indexing_spec.rb
- spec/features/bulk_update_metadata_spec.rb
- spec/features/create_apo_spec.rb
- spec/features/create_collection_spec.rb
- spec/features/create_etd_spec.rb
- spec/features/create_object_h2_spec.rb
- spec/features/create_object_no_files_spec.rb
- spec/features/create_preassembly_image_spec.rb
- spec/features/create_virtual_object_spec.rb
- spec/features/edit_bulk_tags_spec.rb
- spec/spec_helper.rb
- spec/support/deposit_helpers.rb
- spec/support/random_phrase_helpers.rb
- spec/support/xlsx_helpers.rb
Resolves #361 to generate random text using a different source of words than the RandomWord gem.
> Switch source of random text

- spec/features/create_etd_spec.rb
> Timezone fix for ETD test.

- Gemfile.lock
- spec/features/access_indexing_spec.rb
- spec/features/create_apo_spec.rb
- spec/features/create_virtual_object_spec.rb
- spec/features/edit_bulk_tags_spec.rb
To stay up-to-date with sdr-client releases
CI + successful run in stage
> Bump sdr-client to 0.74.0

- spec/features/create_virtual_object_spec.rb
- spec/features/edit_bulk_tags_spec.rb
Once sul-dlss/argo#3318 is merged, we need this change too since the UI will change.
HOLD for the argo PR.
> Bulk edit menu is being renamed to bulk actions

- spec/features/create_apo_spec.rb
Default object rights is now split into view access and download access select boxes.
No
> Fix argo test

- spec/features/create_apo_spec.rb
https://github.com/sul-dlss/argo/pull/3521
> Registration page changes.

- spec/features/access_indexing_spec.rb
- spec/features/create_object_no_files_spec.rb
- spec/features/create_preassembly_image_spec.rb
> Use Add another row button when registering

- spec/features/create_preassembly_image_spec.rb
Test code should be easy to read.
> Avoid unnecessary assignment in test code

- spec/features/access_indexing_spec.rb
The test was broken.
See also sul-dlss/argo/issues/3627 and sul-dlss/argo/issues/3628 for some related tests that should be added but are broken in Argo currently.
> fix broken access-rights integration test

- spec/features/create_apo_spec.rb
fix broken test, possibly broken by https://github.com/sul-dlss/argo/pull/3634
> fix create_apo_spec - cocina model now lazily loaded

- spec/features/create_object_no_files_spec.rb
> Stop looking for process tags

- spec/features/create_preassembly_image_spec.rb
PURL page can sometimes take just a bit longer to be ready, this waits for it in the preassembly spec instead of assuming it will be ready in one second (saw a failure in QA due to it not quite being ready yet).
> wait for purl to actually be done

- .gitignore
- spec/features/access_indexing_spec.rb
- spec/features/create_apo_spec.rb
- spec/features/create_object_no_files_spec.rb
- spec/features/create_preassembly_image_spec.rb
- spec/features/edit_bulk_tags_spec.rb
- spec/support/download_helpers.rb
> Update tests for new argo registration screen

- spec/features/accession_web_archive_spec.rb
Test was failing due to an invalid WARC being generated.
> Fix web archive integration test.

- spec/features/accession_web_archive_spec.rb
Hold for @lwrubel or @edsu or @andrewjbtw or @peterchanws  to sign off
Closes #14
we needed an integration test for web archiving seed objects.  At Ed's suggestion, I folded it into the crawl accession test so the crawl itself can be known to exist.
> accession web archive seed as part of accession_web_archive_spec

- config/settings/staging.yml
- spec/features/accession_web_archive_spec.rb
- spec/support/public_xml_helpers.rb
> Update access_web_archive_spec to verify url in purl xml

- .circleci/config.yml
> Bump orb to 3.1.2

- spec/support/event_helpers.rb
Found a small bug while running the preassembly integration test.
> Ensure the druid is prefixed for dor-services-client

- .rubocop_todo.yml
> add new rubocop config

- spec/features/create_goobi_image_spec.rb
When uploading an image via the goobi UI during the test, we need to wait a bit for the upload to finish before proceeding with the test.
> fix issues with goobi integration test

- config/settings.yml
- config/settings/qa.yml
- config/settings/staging.yml
- spec/features/create_gis_object_spec.rb
- spec/features/gis_accessioning_spec.rb
- spec/support/page_helpers.rb
Add a new integration test for accessioning GIS objects.  Fixes #16 
Note: there is no geoserver-qa, so the test fails part way if run in the QA environment (e.g. see https://argo-qa.stanford.edu/view/druid:sb443ft9972).  
Todo:
> GIS integration test

- spec/features/h2_object_creation_spec.rb
New SunetID lookup field needs a moment to display and then correct Add button needs to be clicked. Now runs on stage and QA.
> Adjusting h2 form input for sunetID lookup

- spec/features/create_object_no_files_spec.rb
- spec/features/gis_accessioning_spec.rb
- spec/features/h2_object_creation_spec.rb
> improve test descriptions

- spec/features/apo_creation_spec.rb
@andrewjbtw requested this - he is sick of scrolling through a zillion names to find his APOs in stage and qa.
> created APOs start with ZZZ

- .rubocop.yml
- spec/features/etd_creation_spec.rb
We're going to have so much winning ...
> add new rubocops and concomittant tweaks to code

- .rubocop.yml
me hate warnings.  (cookie monster)
> avoid rubocop warning

- spec/features/h2_object_creation_spec.rb
To avoid tripping over versions.
> Re-orders h2 test.

- README.md
- config/settings.yml
- spec/support/authentication_helpers.rb
We were coupling to out-of-date Duo/SSO implementation details, apparently?
Yes
> Remove automatic authentication

- spec/spec_helper.rb
> Add a comment

- spec/support/deposit_helpers.rb
Errors were not being reported correctly.
> Tweak so that errors are raised correctly

- Gemfile
- Gemfile.lock
- spec/features/sdr_deposit_spec.rb
- spec/support/deposit_helpers.rb
Get the correct sdr-api client version.
> Upgrades sdr client and fixes tests.

- config/settings/qa.yml
- config/settings/stage.yml
- spec/features/preassembly_hfs_accessioning_spec.rb
- spec/features/preassembly_hsf_accessioning_spec.rb
- spec/features/preassembly_image_accessioning_spec.rb
- spec/support/download_helpers.rb
New integration test for hierarchical file layout
~~HOLD for sul-dlss/pre-assembly#1104, which needs to be merged for this test to work~~
> Preassembly hfs test

- spec/features/h2_object_creation_spec.rb
h2 test was failing without giving the item druid and that was annoying.
> h2 test: get item druid much sooner

- spec/features/h2_globus_creation_spec.rb
> Adds integration test for Globus upload.

- .circleci/config.yml
- .rubocop.yml
- Gemfile.lock
- README.md
Keep pace with Ruby updates
Yes
> Upgrade to Ruby 3.2.2

- spec/features/etd_creation_spec.rb
Wiki page URL has changed, fix it
> fix wiki page URL

- .rubocop.yml
- spec/features/bulk_update_metadata_spec.rb
it's possible to be mindless and productive simultaneously.
> add new rubocops and fixes for them

- config/settings.yml
> Set folio flag to true

- spec/features/etd_creation_spec.rb
Fixes #619
For me, on a fast fiber connection, checking the ETD workflow in argo was happening before the submit-marc and check-marc etdSubmitWF steps were completed, so the test would fail.   This PR fixes that problem.
no need.
> etd spec waits for submit-marc and check-marc steps to complete

- config/settings.yml
- spec/features/item_creation_with_folio_hrid_spec.rb
- spec/features/sdr_deposit_spec.rb
> Remove symphony code.

- .rubocop.yml
- spec/features/bulk_tags_edit_spec.rb
- spec/features/etd_creation_spec.rb
- spec/features/goobi_accessioning_spec.rb
- spec/features/preassembly_hfs_accessioning_spec.rb
- spec/features/preassembly_reaccessioning_spec.rb
> Rubocop update

- spec/features/item_creation_no_files_or_collection_spec.rb
> Test creating and editing an item with no collection.

- spec/support/purl_helpers.rb
> Fix for purl helpers.

- spec/features/preassembly_hfs_accessioning_spec.rb
- spec/features/sdr_deposit_spec.rb
- spec/support/purl_helpers.rb
> Test shelve, publish, and preserve.

- spec/features/bulk_tags_edit_spec.rb
To fix a mistake I added to dep updates.
> revert bulk_tags_edit_spec change

- config/settings.yml
This updates the test to use the new shared path (integration test data has already been copied to the new path)
> Update path to staging data

- Gemfile
- Gemfile.lock
> Update cocina models and DSC

- config/settings.yml
Required by #676 --- left out of that PR by mistake
> add missing gis config

- spec/features/gis_accessioning_spec.rb
the retry with a block is kind of confusing; this is an attempt to help.
> gis test: add a comment

- spec/features/gis_accessioning_spec.rb
- spec/features/preassembly_gis_accessioning_spec.rb
Goes with https://github.com/sul-dlss/gis-robot-suite/pull/785
If we merge that PR, we need to update the expectations so the integration tests continue to pass.
> no more normalized data zip

- spec/features/gis_accessioning_spec.rb
- spec/features/preassembly_gis_accessioning_spec.rb
Quick update to the GIS integration tests to account for new files in structural.
> Update GIS accessioning tests for new file structure

- spec/features/gis_accessioning_spec.rb
Update to test to align with https://github.com/sul-dlss/gis-robot-suite/pull/800/files
Ran test on branch above.
> Check for native map projection not reprojection

- spec/features/preassembly_gis_accessioning_spec.rb
A small fix for the gis preassembly test
> Update test for pre-assembly gis

- spec/features/h2_object_creation_spec.rb
- spec/features/item_creation_no_files_or_collection_spec.rb
> No more Admin type in version selector

- spec/features/h2_object_creation_spec.rb
> Update republish for latest Argo UI.

- spec/features/h2_globus_creation_spec.rb
- spec/features/h2_object_creation_spec.rb
> Fixes H2 deposit.

- spec/features/preassembly_gis_raster_accessioning_spec.rb
- spec/features/preassembly_gis_vector_accessioning_spec.rb
- spec/features/preassembly_hfs_accessioning_spec.rb
- spec/features/preassembly_reaccessioning_spec.rb
This recent change to pre-assembly to deal with accessibility changes requires changes to the integration tests: https://github.com/sul-dlss/pre-assembly/pull/1444
> pre-assembly form changed slightly

- spec/features/gis_accessioning_spec.rb
> Avoid file system sync race condition in gis_accessioning_spec.

- spec/features/preassembly_gis_raster_accessioning_spec.rb
- spec/features/preassembly_gis_vector_accessioning_spec.rb
- spec/features/preassembly_hfs_accessioning_spec.rb
- spec/features/preassembly_ocr_document_spec.rb
- spec/features/preassembly_ocr_image_spec.rb
- spec/features/preassembly_reaccessioning_spec.rb
Requested change to preassembly
> update header in preassembly

- .rubocop.yml
- README.md
> Bump Ruby to 3.3.1

- spec/features/h2_versioned_object_creation_spec.rb
closes #761
Test user versioning from H2.
> Adds H2 versioned test.

- spec/features/h2_globus_creation_spec.rb
- spec/features/h2_object_creation_spec.rb
> Tweaks to H2 tests for user versions and reliability.

- spec/features/h2_versioned_object_creation_spec.rb
> Withdraw and restore user versions.

- spec/features/h2_versioned_object_creation_spec.rb
- spec/support/table_helpers.rb
> Test user versioning-related changes in Purl UI

- spec/features/h2_versioned_object_creation_spec.rb
- spec/support/h2_helpers.rb
> Enable testing of withdrawing a version.

- spec/features/etd_creation_spec.rb
- spec/features/virtual_object_creation_spec.rb
I needed these changes earlier today. :shrug:
> Change a couple tests to help them pass

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
See https://github.com/rails/rails/pull/48847
> Remove unnecessary dependency

- config/settings/qa.yml
- config/settings/stage.yml
- spec/features/h3_object_creation_spec.rb
> Adds H3 object creation spec.

- spec/features/h3_object_creation_spec.rb
> Disable temporarily the selection of a work license in H3 since that is currently not possible

- spec/features/preassembly_speech_to_text_media_spec.rb
It takes about 9 minutes for AWS Batch to provision the EC2 instance and then for the job to complete.
Testing in QA
> Increase speechToText timeout

- spec/features/h3_object_creation_spec.rb
> Handle terms of deposit in H3 spec.

- .circleci/config.yml
- .rubocop.yml
- README.md
- spec/spec_helper.rb
> Bump to Ruby 3.4

- config/settings/stage.yml
It's now configured in both stage and qa
> enable speech to text test in stage

- spec/features/h3_object_creation_spec.rb
There have been a number of updates to H3 in the last week that are breaking for the integration test, this addresses those changes.
> Update h3_object_creation_spec for homepage and for changes

- spec/features/h3_object_creation_spec.rb
> Look for proper homepage text instead of dashboard text

- spec/features/h3_object_creation_spec.rb
So far, this is the only change I think I see holding up the H3 test from passing. I keep hitting a timeout in Argo, but the remainder of the test looks correct at this time.
> Small fix to the h3 creation test

- .gitignore
- spec/features/etd_creation_spec.rb
- spec/features/h3_object_creation_spec.rb
- spec/features/sdr_deposit_spec.rb
* Updates H3 to match current state of development.
* Remove flaky and unnecessary parts of sdr deposit spec.
> Tweak integration tests.

- spec/features/h3_object_creation_spec.rb
NOTE: It still does not pass due to some bugs we are actively working on, but it is better now than it was before.
> Update H3 feature test

- spec/features/goobi_accessioning_spec.rb
Our version of Goobi was upgraded on stage and some small tweaks were required so that Capybara could find elements.
> Adjust to new goobi version HTML

- spec/features/h3_object_creation_spec.rb
This passes for me (woot) although slow and prone to timeout with argo, but this should pass for most.
> Update the H3 integration test for updated label text

- spec/features/preassembly_hfs_accessioning_spec.rb
Likely file system lag issues continue to make this test fail periodically.  This made it pass twice for me after failing consistently.
> bump up timeout a bit to avoid race condition

- spec/features/bulk_tags_edit_spec.rb
- spec/features/virtual_object_creation_spec.rb
These changes should help avoid test failures once https://github.com/sul-dlss/argo/pull/4769 is merged
> Update Argo bulk action names

- spec/features/h3_object_creation_spec.rb
> Fix H3 integration test.

- spec/features/h3_globus_creation_spec.rb
> Update H3 globus test that now requires a draft prior to enabling globus

- spec/features/preassembly_ocr_document_spec.rb
more reliable integration tests (less manual intervention)
(the race condition is between workflow service and the file system)
> preassembly_ocr_document_spec.rb: account for a testing quirk and for a workflow race condition

- spec/features/etd_creation_spec.rb
> Switch etd creation spec to heracles.
